version: '{build}'
branches:
  only:
  - derivative_works/virtual_museum
image: Visual Studio 2019
configuration:
  - Debug
  - Profile
  - Release
platform:
  - Win32
  - x64
shallow_clone: true
build:
  project: VirtualMuseum/Code/Solutions/VirtualMuseum.sln
  parallel: true
  verbosity: minimal
test: off
deploy: off
