version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration:
  - Debug
  - Profile
  - Release
platform:
  - Windows_x86
  - Windows_x64
shallow_clone: true
build_script:
  - msbuild "C:\projects\GITechDemo\GITechDemo\Code\Solutions\GITechDemo.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test: off
deploy: off
