version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration:
  - Debug
  - Profile
  - Release
platform:
  - Windows_x86
  - Windows_x64
shallow_clone: true
build:
  project: GITechDemo/Code/Solutions/GITechDemo.sln
  parallel: true
  verbosity: minimal
test: off
deploy: off
